### ISSUE TITLE
PLEASE HELPE ME, I CAN'T USE THIS!!

### ISSUE THREAD

**Issue by TobiCobain** [Xinerki/kgv-phone#8]
Couldn't load resource kgv-phone: Couldn't load resource kgv-phone from resources:/kgv-phone/: Could not open resource metadata file resources:/kgv-phone//__resource.lua. 
how i can fix it?

**Comment by MajorKorgi** [comment]
Maybe just rename "fxmanifest.lua" to "__resource.lua". I guess the version of your server is too old, so it doesn't recognize the file as a resource metadata file. 
When you've changed that, you have to change "fx_version 'adamant'" into "resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'" of the __resource.lua at the top. 
Otherwise, I don't have a clue what could cause the issue.  
If the problem isn't solved yet, post the full fxmanifest.lua or __resource.lua as a comment below 😄
